sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
services:
  - mongodb
  - redis-server
before_script:
  - npm install -g gulp
script:
  - jshint
  - npm test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6